import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class MockService {

  constructor() { }

  getMock() {
    return [{
      "id": 1,
      "brand": "Chrysler",
      "model": 2008
    }, {
      "id": 2,
      "brand": "Aston Martin",
      "model": 2006
    }, {
      "id": 3,
      "brand": "Acura",
      "model": 1994
    }, {
      "id": 4,
      "brand": "Buick",
      "model": 1991
    }, {
      "id": 5,
      "brand": "Ford",
      "model": 1996
    }, {
      "id": 6,
      "brand": "Mazda",
      "model": 1998
    }, {
      "id": 7,
      "brand": "Toyota",
      "model": 2007
    }, {
      "id": 8,
      "brand": "Ford",
      "model": 2003
    }, {
      "id": 9,
      "brand": "Chevrolet",
      "model": 1998
    }, {
      "id": 10,
      "brand": "Hyundai",
      "model": 2005
    }, {
      "id": 11,
      "brand": "Mazda",
      "model": 1993
    }, {
      "id": 12,
      "brand": "Jeep",
      "model": 2009
    }, {
      "id": 13,
      "brand": "Kia",
      "model": 2009
    }, {
      "id": 14,
      "brand": "Honda",
      "model": 2011
    }, {
      "id": 15,
      "brand": "Lexus",
      "model": 1998
    }, {
      "id": 16,
      "brand": "Lotus",
      "model": 2005
    }, {
      "id": 17,
      "brand": "Pontiac",
      "model": 1979
    }, {
      "id": 18,
      "brand": "Nissan",
      "model": 1993
    }, {
      "id": 19,
      "brand": "Dodge",
      "model": 2009
    }, {
      "id": 20,
      "brand": "Acura",
      "model": 2001
    }, {
      "id": 21,
      "brand": "Isuzu",
      "model": 1992
    }, {
      "id": 22,
      "brand": "Volkswagen",
      "model": 1992
    }, {
      "id": 23,
      "brand": "Mercury",
      "model": 1985
    }, {
      "id": 24,
      "brand": "Honda",
      "model": 1999
    }, {
      "id": 25,
      "brand": "Mercedes-Benz",
      "model": 1998
    }, {
      "id": 26,
      "brand": "Toyota",
      "model": 1999
    }, {
      "id": 27,
      "brand": "Pontiac",
      "model": 1984
    }, {
      "id": 28,
      "brand": "Mitsubishi",
      "model": 2004
    }, {
      "id": 29,
      "brand": "Chrysler",
      "model": 2000
    }, {
      "id": 30,
      "brand": "Dodge",
      "model": 2008
    }, {
      "id": 31,
      "brand": "Ferrari",
      "model": 2009
    }, {
      "id": 32,
      "brand": "Buick",
      "model": 2007
    }, {
      "id": 33,
      "brand": "Dodge",
      "model": 1999
    }, {
      "id": 34,
      "brand": "Cadillac",
      "model": 2007
    }, {
      "id": 35,
      "brand": "Toyota",
      "model": 1997
    }, {
      "id": 36,
      "brand": "Oldsmobile",
      "model": 1999
    }, {
      "id": 37,
      "brand": "Ford",
      "model": 2012
    }, {
      "id": 38,
      "brand": "Chevrolet",
      "model": 2004
    }, {
      "id": 39,
      "brand": "Panoz",
      "model": 2006
    }, {
      "id": 40,
      "brand": "Jeep",
      "model": 2002
    }, {
      "id": 41,
      "brand": "Kia",
      "model": 2001
    }, {
      "id": 42,
      "brand": "Chevrolet",
      "model": 2013
    }, {
      "id": 43,
      "brand": "Nissan",
      "model": 2008
    }, {
      "id": 44,
      "brand": "Chevrolet",
      "model": 1962
    }, {
      "id": 45,
      "brand": "Ford",
      "model": 2004
    }, {
      "id": 46,
      "brand": "Saab",
      "model": 2006
    }, {
      "id": 47,
      "brand": "Ford",
      "model": 1955
    }, {
      "id": 48,
      "brand": "Chrysler",
      "model": 2001
    }, {
      "id": 49,
      "brand": "Jeep",
      "model": 2010
    }, {
      "id": 50,
      "brand": "Ford",
      "model": 2008
    }, {
      "id": 51,
      "brand": "Ford",
      "model": 2000
    }, {
      "id": 52,
      "brand": "Plymouth",
      "model": 1996
    }, {
      "id": 53,
      "brand": "Mazda",
      "model": 2012
    }, {
      "id": 54,
      "brand": "Volkswagen",
      "model": 1996
    }, {
      "id": 55,
      "brand": "Lotus",
      "model": 2010
    }, {
      "id": 56,
      "brand": "Mercedes-Benz",
      "model": 2012
    }, {
      "id": 57,
      "brand": "Audi",
      "model": 1993
    }, {
      "id": 58,
      "brand": "Ford",
      "model": 1987
    }, {
      "id": 59,
      "brand": "GMC",
      "model": 1992
    }, {
      "id": 60,
      "brand": "Ford",
      "model": 2003
    }, {
      "id": 61,
      "brand": "Lotus",
      "model": 1993
    }, {
      "id": 62,
      "brand": "Porsche",
      "model": 1995
    }, {
      "id": 63,
      "brand": "Nissan",
      "model": 1992
    }, {
      "id": 64,
      "brand": "Audi",
      "model": 2000
    }, {
      "id": 65,
      "brand": "Pontiac",
      "model": 1995
    }, {
      "id": 66,
      "brand": "Aston Martin",
      "model": 2006
    }, {
      "id": 67,
      "brand": "Volvo",
      "model": 2003
    }, {
      "id": 68,
      "brand": "Daewoo",
      "model": 2002
    }, {
      "id": 69,
      "brand": "Mercedes-Benz",
      "model": 2006
    }, {
      "id": 70,
      "brand": "MINI",
      "model": 2008
    }, {
      "id": 71,
      "brand": "Lexus",
      "model": 1998
    }, {
      "id": 72,
      "brand": "Volkswagen",
      "model": 2012
    }, {
      "id": 73,
      "brand": "Volvo",
      "model": 1999
    }, {
      "id": 74,
      "brand": "Pontiac",
      "model": 1989
    }, {
      "id": 75,
      "brand": "GMC",
      "model": 1995
    }, {
      "id": 76,
      "brand": "Volkswagen",
      "model": 2010
    }, {
      "id": 77,
      "brand": "Ford",
      "model": 2001
    }, {
      "id": 78,
      "brand": "Chevrolet",
      "model": 2008
    }, {
      "id": 79,
      "brand": "Chevrolet",
      "model": 2004
    }, {
      "id": 80,
      "brand": "Porsche",
      "model": 1994
    }, {
      "id": 81,
      "brand": "Scion",
      "model": 2009
    }, {
      "id": 82,
      "brand": "Mazda",
      "model": 1984
    }, {
      "id": 83,
      "brand": "Lexus",
      "model": 2011
    }, {
      "id": 84,
      "brand": "Lexus",
      "model": 1993
    }, {
      "id": 85,
      "brand": "Mercedes-Benz",
      "model": 2001
    }, {
      "id": 86,
      "brand": "Mercury",
      "model": 1985
    }, {
      "id": 87,
      "brand": "Nissan",
      "model": 2007
    }, {
      "id": 88,
      "brand": "Dodge",
      "model": 2010
    }, {
      "id": 89,
      "brand": "Saab",
      "model": 2005
    }, {
      "id": 90,
      "brand": "Audi",
      "model": 2008
    }, {
      "id": 91,
      "brand": "Ford",
      "model": 1990
    }, {
      "id": 92,
      "brand": "Volkswagen",
      "model": 2011
    }, {
      "id": 93,
      "brand": "Daewoo",
      "model": 2000
    }, {
      "id": 94,
      "brand": "Suzuki",
      "model": 1996
    }, {
      "id": 95,
      "brand": "Cadillac",
      "model": 2011
    }, {
      "id": 96,
      "brand": "BMW",
      "model": 2010
    }, {
      "id": 97,
      "brand": "Honda",
      "model": 1984
    }, {
      "id": 98,
      "brand": "Mazda",
      "model": 1994
    }, {
      "id": 99,
      "brand": "Mercedes-Benz",
      "model": 2007
    }, {
      "id": 100,
      "brand": "Ford",
      "model": 1991
    }];
  }
}
